//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.Tasks.Subgraphs.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLabs.Tasks.Subgraphs.Strings.Strings_RU", typeof(Strings_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить подграф.
        /// </summary>
        internal static string buttonCheckSubgraph {
            get {
                return ResourceManager.GetString("buttonCheckSubgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление рёбер.
        /// </summary>
        internal static string buttonEdges {
            get {
                return ResourceManager.GetString("buttonEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление рёбер выключено.
        /// </summary>
        internal static string buttonEdgesOff {
            get {
                return ResourceManager.GetString("buttonEdgesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление рёбер включено.
        /// </summary>
        internal static string buttonEdgesOn {
            get {
                return ResourceManager.GetString("buttonEdgesOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string buttonHelp {
            get {
                return ResourceManager.GetString("buttonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить набор вершин.
        /// </summary>
        internal static string buttonVertexDialog {
            get {
                return ResourceManager.GetString("buttonVertexDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнение.
        /// </summary>
        internal static string labelComplement {
            get {
                return ResourceManager.GetString("labelComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнение получено, переход ко второму этапу.
        /// </summary>
        internal static string stage1Done {
            get {
                return ResourceManager.GetString("stage1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить этап 1.
        /// </summary>
        internal static string stage1DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage1DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этап 1
        ///На этом этапе вам необходимо в рабочей области построить дополнение данного графа. Перемещать вершины можно при помощи мышки.
        ///
        ///Доступные инструменты:
        ///- Переход в режим добавления/удаления рёбер
        ///- Завершить этап 1
        ///- Справка
        ///
        ///Баллы снимаются при попытке завершить этап при неверно построенном дополнении..
        /// </summary>
        internal static string stage1Help {
            get {
                return ResourceManager.GetString("stage1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное дополнение.
        /// </summary>
        internal static string stage1Mistake1 {
            get {
                return ResourceManager.GetString("stage1Mistake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотека подграфов заполнена.
        /// </summary>
        internal static string stage2Done {
            get {
                return ResourceManager.GetString("stage2Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить этап 2.
        /// </summary>
        internal static string stage2DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage2DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этап 2
        ///На данном этапе вам необходимо построить все возможные попарно неизоморфные подграфы данного графа. Подграф строится в рабочей области, затем добавляется в библиотеку подграфов, расположенную внизу экрана.
        ///
        ///Доступные инструменты:
        ///- Изменение выборки вершин в рабочей области
        ///- Переход в режим добавления/удаления рёбер
        ///- Добавить подграф в библиотеку
        ///- Завершить этап 2
        ///- Справка
        ///
        ///Баллы снимаются при попытке добавить в библиотеку граф, не являющийся подграфом или подграф, изоморфный которому у [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stage2Help {
            get {
                return ResourceManager.GetString("stage2Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный подграф.
        /// </summary>
        internal static string stage2Mistake1 {
            get {
                return ResourceManager.GetString("stage2Mistake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подграф уже имеется в коллекции.
        /// </summary>
        internal static string stage2Mistake2 {
            get {
                return ResourceManager.GetString("stage2Mistake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имеются неучтённые подграфы.
        /// </summary>
        internal static string stage2Mistake3 {
            get {
                return ResourceManager.GetString("stage2Mistake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подграф добавлен в коллекцию.
        /// </summary>
        internal static string stage2Subgraph {
            get {
                return ResourceManager.GetString("stage2Subgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подграф.
        /// </summary>
        internal static string subgraph {
            get {
                return ResourceManager.GetString("subgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вершина.
        /// </summary>
        internal static string vertex {
            get {
                return ResourceManager.GetString("vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите вершины, входящие в подграф.
        /// </summary>
        internal static string vertexDialogInfo {
            get {
                return ResourceManager.GetString("vertexDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление вершин.
        /// </summary>
        internal static string vertexDialogTitle {
            get {
                return ResourceManager.GetString("vertexDialogTitle", resourceCulture);
            }
        }
    }
}
