//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.Tasks.Template.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLabs.Tasks.Template.Strings.Strings_RU", typeof(Strings_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Отменить.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Проверить подграф.
        /// </summary>
        internal static string checkSubgraph {
            get {
                return ResourceManager.GetString("checkSubgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Добавление рёбер.
        /// </summary>
        internal static string edgesCommandButtonDisc {
            get {
                return ResourceManager.GetString("edgesCommandButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Добавление рёбер выключено.
        /// </summary>
        internal static string edgesCommandButtonOff {
            get {
                return ResourceManager.GetString("edgesCommandButtonOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Добавление рёбер включено.
        /// </summary>
        internal static string edgesCommandButtonOn {
            get {
                return ResourceManager.GetString("edgesCommandButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Этап 1
        ///ПУМ ПУМ ПУМ.
        /// </summary>
        internal static string help1 {
            get {
                return ResourceManager.GetString("help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Этап 2
        ///Поздравляем, Вы таки справились с этапом 1!.
        /// </summary>
        internal static string help2 {
            get {
                return ResourceManager.GetString("help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Этап 3
        ///Поздравляем, Вы таки справились с этапом 2!.
        /// </summary>
        internal static string help3 {
            get {
                return ResourceManager.GetString("help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Справка.
        /// </summary>
        internal static string helpButtonDisc {
            get {
                return ResourceManager.GetString("helpButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Имеются неучтённые подграфы.
        /// </summary>
        internal static string info1 {
            get {
                return ResourceManager.GetString("info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Применить.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Дополнение получено, переход ко второму этапу.
        /// </summary>
        internal static string stage1Done {
            get {
                return ResourceManager.GetString("stage1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Завершить этап 1.
        /// </summary>
        internal static string stage1DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage1DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Завершить этап 2.
        /// </summary>
        internal static string stage2DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage2DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Подграф добавлен в коллекцию.
        /// </summary>
        internal static string subgraphAdded {
            get {
                return ResourceManager.GetString("subgraphAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Подграф уже имеется в коллекции.
        /// </summary>
        internal static string subgraphAlreadyAdded {
            get {
                return ResourceManager.GetString("subgraphAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Вершина.
        /// </summary>
        internal static string vertex {
            get {
                return ResourceManager.GetString("vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Изменить набор вершин.
        /// </summary>
        internal static string vertexDialogButton {
            get {
                return ResourceManager.GetString("vertexDialogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Выберите вершины, входящие в подграф.
        /// </summary>
        internal static string vertexDialogInfo {
            get {
                return ResourceManager.GetString("vertexDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Добавление вершин.
        /// </summary>
        internal static string vertexDialogTitle {
            get {
                return ResourceManager.GetString("vertexDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Неверное дополнение.
        /// </summary>
        internal static string wrongComplement {
            get {
                return ResourceManager.GetString("wrongComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Неверный подграф.
        /// </summary>
        internal static string wrongSubgraph {
            get {
                return ResourceManager.GetString("wrongSubgraph", resourceCulture);
            }
        }
    }
}
