//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.Tasks.Template.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLabs.Tasks.Template.Strings.Strings_RU", typeof(Strings_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить подграф.
        /// </summary>
        internal static string buttonCheckSubgraph {
            get {
                return ResourceManager.GetString("buttonCheckSubgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление рёбер.
        /// </summary>
        internal static string buttonEdges {
            get {
                return ResourceManager.GetString("buttonEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление рёбер выключено.
        /// </summary>
        internal static string buttonEdgesOff {
            get {
                return ResourceManager.GetString("buttonEdgesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление рёбер включено.
        /// </summary>
        internal static string buttonEdgesOn {
            get {
                return ResourceManager.GetString("buttonEdgesOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string buttonHelp {
            get {
                return ResourceManager.GetString("buttonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить набор вершин.
        /// </summary>
        internal static string buttonVertexDialog {
            get {
                return ResourceManager.GetString("buttonVertexDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнение.
        /// </summary>
        internal static string labelComplement {
            get {
                return ResourceManager.GetString("labelComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнение получено, переход ко второму этапу.
        /// </summary>
        internal static string stage1Done {
            get {
                return ResourceManager.GetString("stage1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить этап 1.
        /// </summary>
        internal static string stage1DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage1DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этап 1
        ///На этом этапе вам необходимо в рабочей области построить дополнение данного графа. Перемещать вершины можно при помощи мышки.
        ///
        ///Доступные инструменты:
        ///- Переход в режим добавления/удаления рёбер
        ///- Завершить этап 1
        ///- Справка
        ///
        ///Баллы снимаются при попытке завершить этап при неверно построенном дополнении..
        /// </summary>
        internal static string stage1Help {
            get {
                return ResourceManager.GetString("stage1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное дополнение.
        /// </summary>
        internal static string stage1Mistake1 {
            get {
                return ResourceManager.GetString("stage1Mistake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Библиотека подграфов заполнена.
        /// </summary>
        internal static string stage2Done {
            get {
                return ResourceManager.GetString("stage2Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить этап 2.
        /// </summary>
        internal static string stage2DoneButtonDisc {
            get {
                return ResourceManager.GetString("stage2DoneButtonDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этап 2
        ///На данном этапе вам необходимо построить все возможные попарно неизоморфные подграфы данного графа. Подграф строится в рабочей области, затем добавляется в библиотеку подграфов, расположенную внизу экрана.
        ///
        ///Доступные инструменты:
        ///- Изменение выборки вершин в рабочей области
        ///- Переход в режим добавления/удаления рёбер
        ///- Добавить подграф в библиотеку
        ///- Завершить этап 2
        ///- Справка
        ///
        ///Баллы снимаются при попытке добавить в библиотеку граф, не являющийся подграфом или подграф, изоморфный которому у [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string stage2Help {
            get {
                return ResourceManager.GetString("stage2Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный подграф.
        /// </summary>
        internal static string stage2Mistake1 {
            get {
                return ResourceManager.GetString("stage2Mistake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подграф уже имеется в коллекции.
        /// </summary>
        internal static string stage2Mistake2 {
            get {
                return ResourceManager.GetString("stage2Mistake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеются неучтённые подграфы.
        /// </summary>
        internal static string stage2Mistake3 {
            get {
                return ResourceManager.GetString("stage2Mistake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подграф добавлен в коллекцию.
        /// </summary>
        internal static string stage2Subgraph {
            get {
                return ResourceManager.GetString("stage2Subgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подграф.
        /// </summary>
        internal static string subgraph {
            get {
                return ResourceManager.GetString("subgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вершина.
        /// </summary>
        internal static string vertex {
            get {
                return ResourceManager.GetString("vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите вершины, входящие в подграф.
        /// </summary>
        internal static string vertexDialogInfo {
            get {
                return ResourceManager.GetString("vertexDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление вершин.
        /// </summary>
        internal static string vertexDialogTitle {
            get {
                return ResourceManager.GetString("vertexDialogTitle", resourceCulture);
            }
        }
    }
}
